version: '3.9'

services:
  xxl-job-admin:
    platform: linux/amd64
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    networks:
      - net_common
    ports:
      - 8080:8080
    # volumes:
    #   - ./logs:/data/applogs
    environment:
      PARAMS: '
        --spring.datasource.url=jdbc:mysql://luvx:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        --spring.datasource.username=root
        --spring.datasource.password=xxx
        --xxl.job.accessToken=xxl-job-token'
    # extra_hosts:
    #   - luvx:127.0.0.1

networks:
  net_common:
    external: true