# 来源: https://github.com/dockur/windows


services:
  windows:
    image: dockurr/windows-arm
    container_name: windows
    # devices:
    #   - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    environment:
      VERSION: "win11"
      KVM: "N"
    volumes:
      - "$HOME/docker/windows/storage:/storage/shared"

# 来源: https://github.com/11notes/docker-kms
  kms:
    image: 11notes/kms:465f4d1
    container_name: kms
    environment:
      TZ: Europe/Zurich
    volumes:
      - var:/kms/var
    ports:
      - 1688:1688/tcp
  kms-gui:
    image: 11notes/kms-gui:latest
    container_name: kms-gui
    environment:
      TZ: Europe/Zurich
    volumes:
      - var:/kms/var
    ports:
      - 8080:8080/tcp

volumes:
  var: