# 来源: https://github.com/dockur/windows

version: '3.9'

services:
  windows:
    image: dockurr/windows-arm
    container_name: windows
    # devices:
    #   - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    environment:
      VERSION: "win11"
      KVM: "N"
    volumes:
      - "$HOME/docker/windows/storage:/storage/shared"
