version: "3"

services:
  pichome:
    platform: linux/amd64
    image: luvx/pichome
    container_name: pichome
    ports:
      - 80:80
    volumes:
      - "$HOME/docker/pichome/site:/var/www/html"
