services:
  pichome:
    platform: linux/amd64
    image: luvx/pichome:latest
    container_name: pichome
    ports:
      - 80:80
    networks:
      - net_common
    volumes:
      - "$HOME/docker/pichome:/var/www/html"

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    ports:
      - 2342:2342
    networks:
      - net_common
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: xr0926
    volumes:
      - $HOME/docker/photoprism/storage:/photoprism/storage
      - $HOME/docker/photoprism/pictures:/photoprism/originals

networks:
  net_common:
    external: true