version: '3.9'

services:
  postgresql-master:
    image: postgres:latest
    container_name: postgresql-master
    # volumes:
    #   - $HOME/docker/postgresql/logs:/logs
    environment:
      POSTGRES_PASSWORD: xxx
    ports:
      - 5432:5432
