
services:
  postgresql-master:
    image: postgres:latest
    container_name: postgresql-master
    networks:
      - net_common
    volumes:
      - $HOME/docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-boot}
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - 5432:5432

  opengauss:
    image: opengauss:2.0.0
    container_name: opengauss
    networks:
      - net_common
    volumes:
      - /opengauss:/var/lib/opengauss
    privileged: true
    environment:
      - GS_NODENAME=gaussdb
      - GS_USERNAME=gaussdb
      - GS_PASSWORD=Enmo@123
      - GS_PORT=5432
    ports:
      - 55432:5432

networks:
  net_common:
    external: true
