version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - '/root/docker/alist:/opt/alist/data'
        ports:
            - '55244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: alist
        image: 'xhofe/alist:latest'
