version: "3"

services:
  code-server:
    container_name: code-server
    image: codercom/code-server
    ports:
      - "8080:8080"
    volumes:
      - $HOME/code-server:/home/coder/project
      # - $HOME/.config:/home/coder/.config
      # - $HOME/code-server:/home/coder/.local/share/code-server
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PASSWORD: <pw>
      # DOCKER_USER: ${USER}
    restart: always
    # user: ${UID_GID}
