services:
#   bind:
#     platform: linux/amd64
#     image: sameersbn/bind:latest
#     container_name: bind
#     restart: always
#     ports:
#       - '10000:10000/tcp'
#       - '53:53/udp'
#       - '53:53/tcp'
#     networks:
#       - net_common
#     volumes:
#       - $HOME/docker/dns/bind/data:/data
#       - /etc/localtime:/etc/localtime
#     environment:
#       TZ: Asia/Shanghai
#       # ROOT_PASSWORD: password
#     deploy:
#       resources:
#         limits:
#           cpus: '0.50'
#           memory: 300M
#         # reservations:
#         #   cpus: '0.25'
#         #   memory: 200M

  dns-server:
    image: technitium/dns-server:latest
    container_name: dns-server
    hostname: dns-server
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
    volumes:
      - config:/etc/dns
      - $HOME/docker/dns/dns-server/config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000

networks:
  net_common:
    external: true
