version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - $HOME/docker/zk/data:/data
      - $HOME/docker/zk/datalog:/datalog
      - $HOME/docker/zk/logs:/logs
    restart: always
