# mkdir -p $HOME/docker/rocketmq/namesrv/logs
# mkdir -p $HOME/docker/rocketmq/{broker_0,broker_1}/{conf,logs,store}
# echo $HOME/docker/rocketmq/{broker_0,broker_1}/conf | xargs -n 1 cp -v ./broker.conf #修改 brokerName

version: '3.9'

services:
  #Service for nameserver
  namesrv:
    platform: linux/amd64
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - $HOME/docker/rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  #Service for broker
  broker_0:
    platform: linux/amd64
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: broker_0
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - $HOME/docker/rocketmq/broker_0/logs:/home/rocketmq/logs
      - $HOME/docker/rocketmq/broker_0/store:/home/rocketmq/store
      - $HOME/docker/rocketmq/broker_0/conf/broker.conf:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf

  broker_1:
    platform: linux/amd64
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: broker_1
    links:
      - namesrv
    ports:
      - 10929:10909
      - 10931:10911
      - 10932:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - $HOME/docker/rocketmq/broker_1/logs:/home/rocketmq/logs
      - $HOME/docker/rocketmq/broker_1/store:/home/rocketmq/store
      - $HOME/docker/rocketmq/broker_1/conf/broker.conf:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf

  rocketmq-dashboard:
    platform: linux/amd64
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    links:
      - namesrv
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876
