version: "3"

services:
  seata-server:
    image: luvx/sentinel-dashboard:1.8.7
    container_name: sentinel-dashboard
    networks:
      - net_common
    hostname: sentinel-dashboard
    ports:
      - "8080:8080"

networks:
  net_common:
    external: true
