# https://raw.githubusercontent.com/alibaba/nacos/refs/heads/master/distribution/conf/mysql-schema.sql

services:
  nacos0:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos0
    ports:
      - 58080:8080
      - 58848:8848
      - 59848:9848
    networks:
      - net_common
    environment:
      - MODE=standalone
    env_file:
      - ./env/nacos.env

  nacos1:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos1
    networks:
      - net_common
    hostname: nacos1
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    # volumes:
    #   - $HOME/docker/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    #   - $HOME/docker/nacos/logs:/home/nacos/logs
    env_file:
      - ./env/nacos.env

  nacos2:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos2
    networks:
      - net_common
    hostname: nacos2
    ports:
      - "17848:7848"
      - "18848:8848"
      - "19848:9848"
      - "19849:9849"
    env_file:
      - ./env/nacos.env

  nacos3:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos3
    networks:
      - net_common
    hostname: nacos3
    ports:
      - "27848:7848"
      - "28848:8848"
      - "29848:9848"
      - "29849:9849"
    env_file:
      - ./env/nacos.env

networks:
  net_common:
    external: true
