
services:
  influxdb:
    image: bitnami/influxdb:latest
    container_name: influxdb
    networks:
      - net_common
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=password123
      - INFLUXDB_ADMIN_USER_TOKEN=token123

networks:
  net_common:
    external: true
