
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - net_common

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - net_common
    volumes:
      - $HOME/docker/prometheus/conf:/etc/prometheus
      - $HOME/docker/prometheus/data:/prometheus
    # command:
    #   - '--config.file=/etc/prometheus/prometheus.yml'
    #   - '--storage.tsdb.path=/prometheus'
    #   - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    #   - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - net_common
    volumes:
      - $HOME/docker/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus

  # alertmanager:
  #   image: prom/alertmanager
  #   container_name: alertmanager
  #   ports:
  #     - "9093:9093"
  #   networks:
  #     - net_common
  #   volumes:
  #     - $HOME/docker/alertmanager/conf:/etc/alertmanager
  #     - $HOME/docker/alertmanager/data:/var/lib/alertmanager

networks:
  net_common:
    external: true
