services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    ports:
      - 53000:3000
      - 50022:22
    networks:
      - net_common
    volumes:
      - $HOME/docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=luvx.rx:3306
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=xxxx
      - GITEA__database__NAME=gitea


  # act_runner:
  #   image: gitea/act_runner:0.2.10
  #   environment:
  #     - GITEA_INSTANCE_URL=https://example.com/
  #     - GITEA_RUNNER_REGISTRATION_TOKEN=__gitea的runner中获取的加入token__
  #     - GITEA_RUNNER_NAME=docker_runner
  #     - CONFIG_FILE=/config.yaml
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./act_data:/data
  #     - ./act_cache:/root/.cache
  #     - ./config.yaml:/config.yaml
  #   ports:
  #     - 18088:18088

networks:
  net_common:
    external: true
