
services:
  docker:
    # platform: linux/arm64
    image: docker:latest
    container_name: docker
    networks:
      - net_common
    environment:
      - TZ=Asia/Shanghai
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - $HOME/docker/docker/certs-ca:/certs/ca
      - $HOME/docker/docker/certs-client:/certs/client
    privileged: true

# 使用前: /etc/docker/daemon.json
# {
#   "insecure-registries": ["ip:5000"]
# }
  registry:
    image: registry:latest
    container_name: registry
    ports:
      - 5000:5000
    networks:
      - net_common
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $HOME/docker/docker/registry:/var/lib/registry

networks:
  net_common:
    external: true
