services:
  jupyter:
    image: luvx/jupyter:latest
    container_name: jupyter
    ports:
      - 8888:8888
    networks:
      - net_common
    volumes:
      - $HOME/docker/jupyter:/root/code
      - $HOME/.m2:/root/.m2
      - $HOME/go/pkg:/go/pkg
      - $HOME/data:/root/data
    # environment:
    #   - PASSWORD=xxxx


  # showdoc:
  #   image: star7th/showdoc:latest
  #   container_name: showdoc
  #   ports:
  #     - 50080:80
  #   networks:
  #     - net_common
  #   volumes:
  #     - $HOME/docker/showdoc/html:/var/www/html
  #   privileged: true

networks:
  net_common:
    external: true
