services:
  jupyter:
    image: ${ALI_CR:+$ALI_CR/}luvx/jupyter:vscode
    container_name: jupyter
    ports:
      - 8888:8888
      - 8000:8000
    networks:
      - net_common
    volumes:
      - $HOME/OneDrive/Code:/workspace
      - $HOME/code:/workspace/code
      - $HOME/data:/root/data
      - $HOME/go/pkg:/go/pkg
      - $HOME/.m2:/root/.m2
      - $HOME/.continue:/root/.continue
      - $HOME/.dbclient:/root/.dbclient
      - $HOME/.gitconfig:/root/.gitconfig
      - $HOME/.marscode:/root/.marscode
      - $HOME/.oh-my-zsh:/root/.oh-my-zsh
      - vscode:/root/.vscode
      - vscode-server:/root/.vscode-server
    working_dir: /workspace
    environment:
      - TZ=Asia/Shanghai
      # - PASSWORD=xxxx
    # command: jupyter lab --no-browser --allow-root --ip=0.0.0.0 --ServerApp.allow_origin='*' --IdentityProvider.token='' --ServerApp.password='' --ServerApp.disable_check_xsrf=True

  # showdoc:
  #   image: star7th/showdoc:latest
  #   container_name: showdoc
  #   ports:
  #     - 50080:80
  #   networks:
  #     - net_common
  #   volumes:
  #     - $HOME/docker/showdoc/html:/var/www/html
  #   privileged: true

networks:
  net_common:
    external: true

volumes:
  vscode:
  vscode-server:
    external: true
