services:
  jupyter:
    platform: linux/amd64
    image: registry.cn-shanghai.aliyuncs.com/luvx21/luvx_jupyter:latest_amd64
    container_name: jupyter
    ports:
      - 8888:8888
    networks:
      - net_common
    volumes:
      - $HOME/docker/jupyter:/root/code
      - $HOME/.m2:/root/.m2
      - $HOME/go/pkg:/go/pkg
    # environment:
    #   - PASSWORD=xxxx

networks:
  net_common:
    external: true
