version: '3.9'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - net_common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - TZ=Asia/Shanghai
        # - WATCHTOWER_CLEANUP=true                 # 更新后移除旧的镜像
        # - WATCHTOWER_POLL_INTERVAL=30             # 镜像检测时间间隔30秒
        # - WATCHTOWER_NOTIFICATIONS=email
        # - WATCHTOWER_NOTIFICATION_EMAIL_FROM=fromaddress@gmail.com
        # - WATCHTOWER_NOTIFICATION_EMAIL_TO=toaddress@gmail.com
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=fromaddress@gmail.com
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=app_password
        # - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    command: aaa bbb --cleanup --schedule "0 0 4 * * *"
    # --cleanup 更新后清理旧版本镜像
    # --schedule 自动检测更新 crontab定时(限定6位crontab) 此处代表凌晨4点整

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    # ports:
    #   - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg

networks:
  net_common:
    external: true
