version: '3.7'

services:
  mongo:
    image: mongo:4
    container_name: mongo
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - $HOME/docker/mongo/etc/localtime:/etc/localtime:ro
      - $HOME/docker/mongo/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
  mongo-express:
    links:
      - mongo
    image: mongo-express
    container_name: mongo-express
    # restart: always
    ports:
      - 8081:8081
    volumes:
      - $HOME/docker/mongo/express/etc/localtime:/etc/localtime:ro
      - $HOME/docker/mongo/express/data/db:/data/db
    environment:
      # ME_CONFIG_BASICAUTH_USERNAME: admin
      # ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123