version: "3.9"

services:
  shard_config_1:
    image: mongo:7
    container_name: shard_config_1
    command: ["mongod", "--configsvr", "--replSet", "configRS", "--dbpath", "/data/configdb", "--bind_ip_all"]
    networks:
      - net_common
      # shard_cluster:
      #   ipv4_address: 192.168.31.201
  shard_config_2:
    image: mongo:7
    container_name: shard_config_2
    command: ["mongod", "--configsvr", "--replSet", "configRS", "--dbpath", "/data/configdb", "--bind_ip_all"]
    networks:
      - net_common
      # shard_cluster:
      #   ipv4_address: 192.168.31.202


  shard_00_00:
    image: mongo:7
    container_name: shard_00_00
    networks:
      - net_common
      # shard_cluster:
      #   ipv4_address: 192.168.31.211
    command: ["mongod", "--shardsvr", "--replSet", "shard_00", "--dbpath", "/data/db", "--bind_ip_all"]
  shard_00_01:
    image: mongo:7
    container_name: shard_00_01
    networks:
      - net_common
      # shard_cluster:
      #   ipv4_address: 192.168.31.212
    command: ["mongod", "--shardsvr", "--replSet", "shard_00", "--dbpath", "/data/db", "--bind_ip_all"]

  shard_01_00:
    image: mongo:7
    container_name: shard_01_00
    networks:
      - net_common
      # shard_cluster:
      #   ipv4_address: 192.168.31.213
    command: ["mongod", "--shardsvr", "--replSet", "shard_01", "--dbpath", "/data/db", "--bind_ip_all"]
  shard_01_01:
    image: mongo:7
    container_name: shard_01_01
    networks:
      - net_common
      # shard_cluster:
      #   ipv4_address: 192.168.31.214
    command: ["mongod", "--shardsvr", "--replSet", "shard_01", "--dbpath", "/data/db", "--bind_ip_all"]

  shard_router:
    image: mongo:7
    container_name: shard_router
    ports:
      - 27017:27017
    command: ["mongos", "--configdb", "configRS/shard_config_1:27019,shard_config_2:27019", "--bind_ip_all"]
    networks:
      - net_common
      # shard_cluster:
      #   ipv4_address: 192.168.31.221
    depends_on:
      - shard_config_1
      - shard_config_2

# networks:
#   shard_cluster:
#     ipam:
#       config:
#         - subnet: 192.168.31.0/24

networks:
  net_common:
    external: true
