global:
  resolve_timeout: 5m
  smtp_smarthost: 'email-smtp.ap-southeast-1.amazonaws.com:465'
  smtp_from: 'xxx@xxx.com'
  smtp_auth_username: 'xxx'
  smtp_auth_password: 'xxx'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: 'demoalert'

receivers:
  - name: 'demoalert'
    email_configs:
      - to: 'xxx@xxx.com'
