version: '3'

services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    container_name: single-es
    networks:
      - net_common
    ports:
      - 9200:9200
      - 9300:9300
    # volumes:
      # - $HOME/docker/single-es/data:/usr/share/elasticsearch/data # 数据文件挂载
      # - $HOME/docker/single-es/plugins:/usr/share/elasticsearch/plugins # 插件文件挂载
      # - $HOME/docker/single-es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - TZ=Asia/Shanghai
      - /etc/localtime:/etc/localtime
      - node.name=single-es
      - cluster.name=${CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" # 设置使用jvm内存大小
      - discovery.type=single-node # 以单一节点模式启动
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: kibana:${STACK_VERSION}
    container_name: single-kibana
    networks:
      - net_common
    ports:
      - 5601:5601
    # volumes:
    #   - kibana_data:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://single-es:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    mem_limit: ${MEM_LIMIT}
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:${STACK_VERSION}
    container_name: single-logstash
    networks:
      - net_common
    ports:
      - 4560:4560
      - 5044:5044
      # - 8080:8080
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      # - $HOME/docker/single-logstash/conf:/config-dir
      # - $HOME/docker/single-logstash/patterns:/opt/logstash/patterns
      # - $HOME/docker/single-logstash/logstash.yml:/usr/share/logstash/config/logstash.yml # 挂载logstash的配置文件
      # - $HOME/docker/single-logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - TZ=Asia/Shanghai
      - /etc/localtime:/etc/localtime
      - xpack.monitoring.enabled=false
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:${STACK_VERSION}
    container_name: single-filebeat
    user: root
    networks:
      - net_common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro

      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # - $HOME/docker/filebeat/data:/usr/share/filebeat/data
      # - $HOME/docker/filebeat/logs:/usr/share/filebeat/logs
      # - /usr/local/nginx/logs:/var/log/nginx # 测试用
    environment:
      - TZ=Asia/Shanghai
      - /etc/localtime:/etc/localtime
      - strict.perms=false
    depends_on:
      - logstash

volumes:
  kibana_data:
    driver: local

networks:
  net_common:
    external: true