
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - net_common
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/docker/portainer/data:/data:rw

  dockge:
    image: louislam/dockge:1
    container_name: dockge
    networks:
      - net_common
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/docker/dockge/data:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - ../:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks

  dpanel:
    image: dpanel/dpanel:latest
    container_name: dpanel
    networks:
      - net_common
    ports:
      # - 80:80
      # - 443:443
      - 58807:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/docker/dpanel:/dpanel
    environment:
      - APP_NAME=dpanel
      - INSTALL_USERNAME=admin
      - INSTALL_PASSWORD=admin

networks:
  net_common:
    external: true
