version: '3.9'
services:
  mysql-master:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql-master
    network_mode: net_common
    privileged: true
    user: 501:20
    volumes:
      - $HOME/docker/mysql/mysql_0/data/:/var/lib/mysql
      - $HOME/docker/mysql/mysql_0/logs/:/var/log/mysql
      - $HOME/docker/mysql/mysql_0/conf/:/etc/mysql
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - $HOME/docker/mysql/mysql_0/init/:/docker-entrypoint-initdb.d
      - $HOME/docker/mysql/mysql_0/my.cnf:/etc/my.cnf
    # command: [
    #     '--character-set-server=utf8mb4',
    #     '--collation-server=utf8mb4_general_ci',
    #     'lower-case-table-names=1',
    #     '--max_connections=3000'
    # ]
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      # MYSQL_USER: xxx
      # MYSQL_PASSWORD: xxx
      MYSQL_DATABASE: xxx
      TZ: Asia/Shanghai
    ports:
      - 53306:3306

  mysql-slave-1:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql-slave-1
    depends_on:
      - mysql-master
    network_mode: net_common
    privileged: true
    user: 501:20
    volumes:
      - $HOME/docker/mysql/mysql_1/data/:/var/lib/mysql
      - $HOME/docker/mysql/mysql_1/logs/:/var/log/mysql
      - $HOME/docker/mysql/mysql_1/conf/:/etc/mysql
      - $HOME/docker/mysql/mysql_1/init/:/docker-entrypoint-initdb.d
      - $HOME/docker/mysql/mysql_1/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      # MYSQL_USER: xxx
      # MYSQL_PASSWORD: xxx
      TZ: Asia/Shanghai
    ports:
      - 53307:3306

  mysql-slave-2:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql-slave-2
    depends_on:
      - mysql-slave-1
    network_mode: net_common
    privileged: true
    user: 501:20
    volumes:
      - $HOME/docker/mysql/mysql_2/data/:/var/lib/mysql
      - $HOME/docker/mysql/mysql_2/logs/:/var/log/mysql
      - $HOME/docker/mysql/mysql_2/conf/:/etc/mysql
      - $HOME/docker/mysql/mysql_2/init/:/docker-entrypoint-initdb.d
      - $HOME/docker/mysql/mysql_2/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      # MYSQL_USER: xxx
      # MYSQL_PASSWORD: xxx
      TZ: Asia/Shanghai
    ports:
      - 53308:3306