version: '3'
services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - $HOME/docker/mysql/data/:/var/lib/mysql
      - $HOME/docker/mysql/logs/:/var/log/mysql
      - $HOME/docker/mysql/conf/:/etc/mysql
      - $HOME/docker/mysql/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      # - /apps/mysql/source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_USER: xxx
      MYSQL_PASSWORD: xxx
      MYSQL_DATABASE: xxx
      TZ: Asia/Shanghai
    ports:
      - 53306:3306