
services:
  ollama:
    image: ${DOCKERHUB_MIRROR}/ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    networks:
      - net_common
    volumes:
      - $HOME/docker/ollama/aaa:/root/.ollama
    environment:
      - TZ=Asia/Shanghai

# fastgpt
  open-webui:
    image: ${GH_CR_NJU}/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 48080:8080
    networks:
      - net_common
    environment:
      - OLLAMA_BASE_URL=http://ollama
    volumes:
      - open-webui:/app/backend/data

  one-api:
    platform: linux/amd64
    image: ${GH_CR_NJU}/songquanpeng/one-api
    container_name: one-api
    ports:
      - 3000:3000
    networks:
      - net_common
    environment:
      - TZ=Asia/Shanghai
      # 使用 MySQL
      # - SQL_DSN="root:123456@tcp(localhost:3306)/oneapi"
    volumes:
      - $HOME/docker/one-api/data:/data

networks:
  net_common:
    external: true
volumes:
    open-webui: