version: '3.3'
services:
    zookeeper1:
        image: zookeeper
        container_name: zookeeper1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888 server.4=zookeeper4:2888:3888:observer
    zookeeper2:
        image: zookeeper
        container_name: zookeeper2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888 server.4=zookeeper4:2888:3888:observer
    zookeeper3:
        image: zookeeper
        container_name: zookeeper3
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888 server.4=zookeeper4:2888:3888:observer
    zookeeper4:
        image: zookeeper
        container_name: zookeeper4
        ports:
            - "2184:2181"
        environment:
            ZOO_MY_ID: 4
            PEER_TYPE: observer
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888 server.4=zookeeper4:2888:388:observer

    kafka1:
        image: wurstmeister/kafka
        container_name: kafka1
        ports:
          - "9092:9092"
        depends_on:
          - zookeeper1
          - zookeeper2
          - zookeeper3
          - zookeeper4
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ADVERTISED_HOST_NAME: kafka1
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_HOST_NAME: kafka1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181
          KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    kafka2:
        image: wurstmeister/kafka
        container_name: kafka2
        ports:
          - "9093:9092"
        depends_on:
          - zookeeper1
          - zookeeper2
          - zookeeper3
          - zookeeper4
        environment:
          KAFKA_BROKER_ID: 2
          KAFKA_ADVERTISED_HOST_NAME: kafka2
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_HOST_NAME: kafka2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181
          KAFKA_LISTENERS: PLAINTEXT://kafka2:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    kafka3:
        image: wurstmeister/kafka
        container_name: kafka3
        ports:
          - "9094:9092"
        depends_on:
          - zookeeper1
          - zookeeper2
          - zookeeper3
          - zookeeper4
        environment:
          KAFKA_BROKER_ID: 3
          KAFKA_ADVERTISED_HOST_NAME: kafka3
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_HOST_NAME: kafka3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181
          KAFKA_LISTENERS: PLAINTEXT://kafka3:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
