version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://luvx:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "foobar:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # kafka:
  #   image: wurstmeister/kafka:2.13-2.6.0
  #   ports:
  #     - "9092:9092"
  #     - "9094:9094"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_LISTENERS: INSIDE://kafka:9094,OUTSIDE://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://luvx:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "foobar:1:1"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
