version: '3.9'

services:
  golang:
    # image: golang:1.22
    image: bitnami/golang:1.22
    container_name: golang
    networks:
      - net_common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/go/pkg/mod:/go/pkg/mod # GOPATH
      - $HOME/go/src:/go/src
    environment:
        - TZ=Asia/Shanghai
    tty: true # Enables debugging capabilities when attached to this container.
    command: ["sleep", "infinity"] # To keep the container running

networks:
  net_common:
    external: true
