# mkdir -p $HOME/docker/redis/{data,logs}
# touch $HOME/docker/redis/redis.conf

version: '3.9'

services:
  redis-stack-server:
    image: ${STACK_IMAGE}:${REDIS_STACK_VERSION}
    container_name: redis-stack-server
    ports:
      - 6379:6379
    networks:
      - net_common
    # restart: always
    volumes:
      - $HOME/docker/redis/redis.conf:/etc/redis/redis.conf:ro
      - $HOME/docker/redis/data:/data
      - $HOME/docker/redis/logs:/logs
    # command: redis-server /etc/redis/redis.conf

  RedisInsight:
    platform: linux/amd64
    image: luvx/redisinsight:latest
    container_name: RedisInsight
    ports:
      - 8001:8001
    networks:
      - net_common
    volumes:
      - $HOME/docker/RedisInsigh:/data
    # environment:
    #   RI_CLIENTS_MAX_RETRIES_PER_REQUEST: 1

networks:
  net_common:
    external: true
