services:
  redis-master:
    image: redis:${REDIS_VERSION}
    container_name: redis-master
    networks:
      - net_common
    ports:
      - 6379:6379
    volumes:
      - $HOME/docker/redis_replicaset:/data
    command: redis-server --requirepass ${PASSWORD}

  redis-slave-1:
    image: redis:${REDIS_VERSION}
    container_name: redis-slave-1
    networks:
      - net_common
    depends_on:
      - redis-master
    ports:
      - 16379:6379
    command: redis-server --slaveof redis-master 6379 --requirepass ${PASSWORD} --masterauth ${PASSWORD}

  redis-slave-2:
    image: redis:${REDIS_VERSION}
    container_name: redis-slave-2
    networks:
      - net_common
    depends_on:
      - redis-master
    ports:
      - 26379:6379
    command: redis-server --slaveof redis-master 6379 --requirepass ${PASSWORD} --masterauth ${PASSWORD}

  redis-slave-3:
    image: redis:${REDIS_VERSION}
    container_name: redis-slave-3
    networks:
      - net_common
    depends_on:
      - redis-slave-2
    ports:
      - 36379:6379
    command: redis-server --slaveof redis-slave-2 6379 --requirepass ${PASSWORD} --masterauth ${PASSWORD}

networks:
  net_common:
    external: true
