# mkdir -p $HOME/docker/redis/{data,logs}
# touch $HOME/docker/redis/redis.conf

version: '3.9'

services:
  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    networks:
      - net_common
    # restart: always
    volumes:
      - $HOME/docker/redis/redis.conf:/etc/redis/redis.conf:ro
      - $HOME/docker/redis/data:/data
      - $HOME/docker/redis/logs:/logs
    # command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
      - 8001:8001

  RedisInsight:
    platform: linux/amd64
    image: luvx/redisinsight:latest
    container_name: RedisInsight
    ports:
      - 8001:8001
    networks:
      - net_common
    volumes:
      - $HOME/docker/RedisInsigh:/data

networks:
  net_common:
    external: true
