version: '3.9'

services:
  pulsar:
    image: apachepulsar/pulsar:${PULSAR_VERSION}
    container_name: pulsar
    ports:
      - 6650:6650
      - 8080:8080
    networks:
      - net_common
    # volumes:
    #   - source: pulsardata:/pulsar/data
    #   - source: pulsarconf:/pulsar/conf
    # environment:
    #   - PULSAR_PREFIX_clusterName=cluster_single
    command: bin/pulsar standalone
    # command: sh -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"

  pulsar-manager:
    platform: linux/amd64
    image: apachepulsar/pulsar-manager:latest
    container_name: pulsar-manager
    networks:
      - net_common
    ports:
      - 9527:9527
      - 7750:7750
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties

networks:
  net_common:
    external: true