name: 构建docker镜像

on:
  workflow_dispatch:
    inputs:
      image:
        description: '镜像名称'
        required: true
      tag:
        description: '镜像版本/代码分支'
        required: true
      buildArg:
        description: 'Dockerfile的构建参数, arg1=foo arg2=bar'
        required: false
        default: ''
      platform:
        description: '架构'
        required: true
        default: 'linux/arm64,linux/amd64'
        type: choice
        options:
          - linux/arm64,linux/amd64
          - linux/arm64
          - linux/amd64
      custom_arg:
        description: '自定义参数'
        required: false
        default: ''

env:
  REGISTRY_USER: "${{ secrets.REGISTRY_USER }}"
  REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"

jobs:
  build:
    name: 构建镜像
    runs-on: ubuntu-latest
    steps:
      - name: 参数信息
        run: |
          echo "=============================================================================="
          echo ${{ inputs.image }}
          echo ${{ inputs.tag }}
          echo "=============================================================================="
      - name: 代码检出
        uses: actions/checkout@v4
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: 登录到Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: 磁盘信息
        run: |
          echo "磁盘信息"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
      - name: 构建
        env:
          CUSTOM_ARG: {{ inputs.custom_arg }}
        run: |
          repository=${{ inputs.image }}
          tag=${{ inputs.tag }}
          buildArg=${{ inputs.buildArg }}
          platform=${{ inputs.platform }}

          minor=${tag%.*}
          major=${tag%%.*}
          if [[ -n $buildArg ]]; then
            for arg in $buildArg; do
              temp+="--build-arg $arg"
            done
            buildArg=$temp
          fi

          case "${repository}" in
            "chartdb")
              url=https://github.com/chartdb/chartdb.git#v$tag
              ;;
            "dicedb")
              url=https://github.com/DiceDB/dice.git#v$tag
              ;;
            "json4u")
              url=https://github.com/loggerhead/json4u.git#v$tag
              ;;
            "jupyter")
              url=https://github.com/LuVx21/docker-compose-files.git#master:jupyter
              url="./jupyter"
              ;;
            "pichome")
              url=https://github.com/zyx0814/Pichome-docker.git
              ;;
            "sentinel-dashboard")
              curl https://raw.githubusercontent.com/alibaba/Sentinel/master/sentinel-dashboard/Dockerfile > ./sentinel-dashboard/Dockerfile
              cd sentinel-dashboard && sed -i "" "s/1.8.6/1.8.8/g" Dockerfile && sed -i "" "s/amd64\///g" Dockerfile
              ;;
            "base-0"|"base-1"|"base-2"|"ops"|"oracle_jdk"|"graalvm_jdk"|"mvnd"|"vscode"|"upx"|"duckdb"|"rocketmq-dashboard")
              url=https://github.com/LuVx21/docker-compose-files.git#master:luvx
              url="./luvx"
              target="--target $repository"
              ;;
            *)
              # exit 0
            ;;
          esac;

          image="luvx/$repository"
          echo "构建镜像: ${image} 版本: ${tag}, ${minor}, ${major} 架构: ${platform} 构建参数: ${buildArg} 上下文: ${url} 自定义参数: ${CUSTOM_ARG}"

          echo "执行命令: docker buildx build --push ${buildArg} ${target} --platform ${platform} -t ${image}:latest -t ${image}:${tag} -t ${image}:${minor} -t ${image}:${major} ${url} ${CUSTOM_ARG}"
          docker buildx build --push ${buildArg} ${target} \
            --platform ${platform} \
            -t ${image}:latest \
            -t ${image}:${tag} \
            -t ${image}:${minor} \
            -t ${image}:${major} \
            ${url} ${CUSTOM_ARG}
      - name: 磁盘信息
        run: |
          echo "磁盘信息"
          echo "=============================================================================="
          df -hT
          docker system df
          echo "=============================================================================="
      - name: 清理磁盘
        run: docker system prune -f